name: CMake Build

on:
  create:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
    - name: Install dependencies (ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libtbb-dev
    - name: Install dependencies (macOS)
      if: matrix.os == 'macOS-latest'
      run: |
        brew install tbb
    - name: Build
      run: |
        cmake -B build
        cmake --build build
