name: CMake Build OSX

on:
  create:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
    - name: Build
      run: |
        cmake -B build
        cmake --build build
    - name: Rename File (OSX)
      run: mv build/42CC build/42CC-mac
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifactErrorsFailBuild: false
        artifacts: "build/42CC-mac,build/resources.42CC"
        draft: false
        makeLatest: true
        prerelease: true
        replacesArtifacts: false
        skipIfReleaseExists: false

